### ISSUE TITLE
Load tested?

### ISSUE THREAD

**Issue by mrfamazing** [vinguan/payloadion#1]
I'm curious if this library is being used in a production environment with apple and how heavy of a load is being used against it?

**Comment by vinguan** [comment]
This library does not send notifications to APNS or others Push Notification services. It onlys build the payloads for yout to send to them. It's really useful to use with Azure Notification Hubs for example. I am using in 1 app in a production envoiroment. But it is a really new library. If you get any issue open it here and send me the pull-requests if you know how to fix-it. I will be really thankfull.
